/* 灵感集市演示应用：数据仅保存在浏览器 localStorage */
const A='png/';
const products=[
 {id:'p1',cat:'painting',name:'人物头像·半身插画',price:199,img:A+'[002566].png',seller:'小满工作室',desc:'温柔细腻的数字人物插画，适合头像、礼物与社交媒体使用。交付 PNG 高清文件。',isNew:true},
 {id:'p2',cat:'painting',name:'原创角色立绘设计',price:499,img:A+'oc1 (1).png',seller:'阿柚插画',desc:'从设定到上色的一站式原创角色立绘，包含两次修改。',isNew:true},
 {id:'p3',cat:'logo',name:'品牌 Logo 定制',price:899,img:A+'disign2.png',seller:'方圆设计',desc:'Logo、标准字与基础色彩规范，适合初创品牌建立第一套视觉识别。',isNew:true},
 {id:'p4',cat:'logo',name:'极简品牌视觉包',price:1599,img:A+'未命名作品.png',seller:'木子视觉',desc:'Logo + 名片 + 社交头像 + 品牌使用规范，交付源文件。'},
 {id:'p5',cat:'print',name:'艺术微喷·装饰画',price:79,img:A+'绘画委托 12.png',seller:'纸间印务',desc:'高品质艺术微喷，支持多尺寸定制，默认 30×40cm。'},
 {id:'p6',cat:'print',name:'品牌贴纸印刷 100 张',price:129,img:A+'委托.png',seller:'纸间印务',desc:'防水哑膜贴纸印刷，适合包装、伴手礼和活动周边。'}
];
const cats={painting:['绘画商品','原创插画、头像与角色设计','发现能代表你的独特画面'],logo:['Logo设计','从一个符号，建立品牌记忆','让品牌被看见，也被记住'],print:['印刷服务','把屏幕上的好设计，变成手里的质感','小批量也能拥有专业品质']};
const customCopy={painting:'一对一绘画定制：描述你的想法，创作者会先沟通需求与报价。',logo:'一对一品牌定制：从品牌定位、Logo 到视觉规范，按需求定制方案。',print:'一对一印刷定制：选择尺寸、材质与数量，商家为你核算专属报价。'};
const seed={users:[{id:'u1',name:'演示买家',email:'buyer@demo.com',password:'123456',role:'buyer'},{id:'m1',name:'方圆设计',email:'merchant@demo.com',password:'123456',role:'merchant'}],cart:[],orders:[],messages:[{id:1,from:'方圆设计',fromRole:'merchant',text:'你好！需要 Logo 设计可以先告诉我品牌方向。',time:'刚刚'}],products:products.map(p=>({...p,active:true}))};
function load(){let d=JSON.parse(localStorage.getItem('linggan-data')||'null');if(!d){d=seed;save(d)}(d.orders||[]).forEach(o=>{o.status={待确认:'确认',制作中:'等待交货',待收货:'等待交货',已完成:'完成'}[o.status]||o.status});return d}
function save(d){localStorage.setItem('linggan-data',JSON.stringify(d))}
let data=load();
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function current(){return data.users.find(u=>u.id===localStorage.getItem('linggan-user'))}
function go(path){location.hash=path}
function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function requireLogin(next){if(!current()){toast('请先登录后继续');go('/login?next='+encodeURIComponent(next));return false}return true}
function productCard(p){return `<article class="product-card"><a href="#/product/${p.id}"><img src="${p.img}" alt="${esc(p.name)}" onerror="this.style.background='#eee'"><div class="product-info"><span class="tag">${cats[p.cat][0]}</span><h3>${esc(p.name)}</h3><p class="muted">${esc(p.seller)}</p><span class="price">¥${p.price}</span></div></a></article>`}
function shell(title,body){return `<section class="section"><div class="section-head"><div><p class="eyebrow">${title.toUpperCase()}</p><h2>${title}</h2></div></div>${body}</section>`}
function home(){let active=data.products.filter(p=>p.active),newProducts=active.filter(p=>p.isNew);return `<section class="hero hero-no-art"><div><p class="eyebrow">FIND YOUR CREATIVE PARTNER</p><h1>让灵感<br><i>落地成真</i></h1><p>连接创作者与有想法的人。无论是一幅画、一个 Logo，还是一份印刷品，在这里找到适合你的设计服务。</p><a class="btn" href="#/category/painting">开始探索</a><a class="btn secondary" href="#/merchant">我是设计师</a></div></section>${shell('探索分类',`<div class="category-grid">${Object.entries(cats).map(([id,c])=>`<a class="category-card" href="#/category/${id}"><span>0${Object.keys(cats).indexOf(id)+1}</span><strong>${c[0]}</strong><span>${c[1]}</span><p>${c[2]} →</p></a>`).join('')}</div>`)}${shell('新品上架',`<div class="product-grid">${(newProducts.length?newProducts:active).slice(0,4).map(productCard).join('')}</div><p><a class="btn secondary" href="#/category/painting">查看更多 →</a></p>`)}${shell('精选服务',`<div class="product-grid">${active.slice(0,4).map(productCard).join('')}</div><p><a class="btn secondary" href="#/category/painting">查看全部服务 →</a></p>`)}<section class="section notice"><b>新用户福利</b>　注册即享首单咨询，平台担保交易，设计不满意可申请售后。</section>${welcomeModal()}`}
function welcomeModal(){return `<div class="welcome-modal" id="welcome-modal" role="dialog" aria-modal="true" aria-labelledby="welcome-title"><div class="welcome-backdrop" onclick="closeWelcome()"></div><div class="welcome-panel"><button class="welcome-close" aria-label="关闭弹窗" onclick="closeWelcome()">×</button><span class="welcome-icon">✦</span><p class="eyebrow">WELCOME TO 灵感集市</p><h2 id="welcome-title">把你的想法，<br><i>交给合适的人。</i></h2><p>探索绘画、Logo 设计与印刷服务，或直接发起一次定制咨询。</p><div><a class="btn" href="#/category/painting" onclick="closeWelcome()">开始逛逛</a><button class="btn secondary" onclick="closeWelcome()">稍后再看</button></div></div></div>`}
function closeWelcome(){let modal=$('#welcome-modal');if(modal){modal.classList.add('is-closing');setTimeout(()=>modal.remove(),220)}}
function category(id,view='product'){let c=cats[id];if(!c)return home();let ps=data.products.filter(p=>p.cat===id&&p.active);let custom=`<div class="admin-card"><span class="tag">定制服务</span><h3>${c[0]} · 专属定制</h3><p>${customCopy[id]}</p><button class="btn" onclick="consultCategory('${id}')">登录后咨询定制</button></div>`;return `<section class="hero" style="padding-top:55px;padding-bottom:55px"><div><p class="eyebrow">CATEGORY / ${id}</p><h1>${c[0]}</h1><p>${c[1]}。${c[2]}。</p></div></section>${shell(c[0],`<div class="tabs"><button class="${view==='product'?'active':''}" onclick="go('/category/${id}?view=product')">产品（${ps.length}）</button><button class="${view==='custom'?'active':''}" onclick="go('/category/${id}?view=custom')">定制服务</button></div>${view==='custom'?custom:`<div class="product-grid">${ps.length?ps.map(productCard).join(''):'<div class="empty" style="grid-column:1/-1"><strong>○</strong>该分类暂时没有产品</div>'}</div>`}`)}`}
function consultCategory(id){if(!requireLogin('/category/'+id+'?view=custom'))return;data.messages.push({id:Date.now(),from:'买家',fromRole:'buyer',text:'我想咨询'+cats[id][0]+'定制服务',time:'刚刚'});save(data);go('/messages')}
function product(id){let p=data.products.find(x=>x.id===id);if(!p)return shell('找不到服务','<div class="empty">服务不存在或已下架</div>');return `<div class="detail"><div class="detail-grid"><div><img class="detail-img" src="${p.img}" alt="${esc(p.name)}"></div><div><span class="tag">${cats[p.cat][0]}</span><h1>${esc(p.name)}</h1><p class="muted">创作者：${esc(p.seller)}</p><p>${esc(p.desc)}</p><div class="price">¥${p.price}</div><div class="option"><b>交付周期</b><br><span class="muted">确认需求后 3-7 个工作日</span></div><div class="qty"><button onclick="changeQty(-1)">−</button><b id="qty">1</b><button onclick="changeQty(1)">+</button></div><button class="btn" onclick="addCart('${p.id}')">加入菜篮</button> <button class="btn secondary" onclick="consult('${p.seller}')">咨询创作者</button></div></div></div>`}
let qty=1;function changeQty(n){qty=Math.max(1,qty+n);$('#qty').textContent=qty}function addCart(id){if(!requireLogin('/product/'+id))return;for(let i=0;i<qty;i++)data.cart.push(id);save(data);updateBadges();toast('已加入菜篮');}function consult(name){if(!requireLogin('/messages'))return;data.messages.push({id:Date.now(),from:name,text:'我想咨询定制服务',time:'刚刚'});save(data);go('/messages')}
function cart(){if(!current())return shell('菜篮','<div class="empty"><strong>🧺</strong>登录后查看你的菜篮<br><a class="btn" href="#/login">去登录</a></div>');let rows=data.cart.map((id,i)=>{let p=data.products.find(x=>x.id===id);return p?`<div class="cart-row"><img src="${p.img}" alt=""><div class="grow"><b>${esc(p.name)}</b><p class="muted">${esc(p.seller)}</p></div><span class="price">¥${p.price}</span><button onclick="removeCart(${i})">删除</button></div>`:''}).join('');let total=data.cart.reduce((s,id)=>s+(data.products.find(p=>p.id===id)?.price||0),0);return shell('我的菜篮',rows||'<div class="empty"><strong>🧺</strong>菜篮还是空的，去逛逛吧</div>')+(rows?`<div class="section total">合计：<b class="price">¥${total}</b><br><button class="btn" onclick="checkout()">提交订单</button></div>`:'')}
function removeCart(i){data.cart.splice(i,1);save(data);render()}
function checkout(){if(!requireLogin('/cart'))return;let ids=[...data.cart];if(!ids.length)return;data.orders.unshift({id:'LG'+Date.now().toString().slice(-7),items:ids,status:'未付款',date:new Date().toLocaleDateString('zh-CN'),total:ids.reduce((s,id)=>s+(data.products.find(p=>p.id===id)?.price||0),0)});data.cart=[];save(data);toast('订单已提交，请完成付款');go('/orders')}
function auth(register=false){return `<div class="form-wrap"><p class="eyebrow">WELCOME</p><h1>${register?'创建账号':'欢迎回来'}</h1><p class="muted">${register?'加入灵感集市，开启创作之旅':'登录后可以购买服务、咨询创作者'}</p><form onsubmit="authSubmit(event,${register})"><div class="field"><label>邮箱</label><input name="email" type="email" required placeholder="you@example.com"></div>${register?'<div class="field"><label>昵称</label><input name="name" required placeholder="你的称呼"></div>':''}<div class="field"><label>密码</label><input name="password" type="password" minlength="6" required placeholder="至少 6 位"></div><button class="btn full">${register?'注册':'登录'}</button></form><p class="muted">演示账号：buyer@demo.com / 123456<br>商家账号：merchant@demo.com / 123456</p><a class="switch" href="#/${register?'login':'register'}">${register?'已有账号？去登录':'还没有账号？免费注册'}</a></div>`}
function authSubmit(e,register){e.preventDefault();let f=new FormData(e.target),email=f.get('email'),u=data.users.find(x=>x.email===email);if(register){if(u)return toast('该邮箱已注册');u={id:'u'+Date.now(),email,name:f.get('name'),password:f.get('password'),role:'buyer'};data.users.push(u)}else if(!u||u.password!==f.get('password'))return toast('邮箱或密码不正确');localStorage.setItem('linggan-user',u.id);save(data);toast(register?'注册成功':'登录成功');let next=new URLSearchParams(location.hash.split('?')[1]).get('next');go(next||'/')}
function orderActions(o){if(o.status==='未付款')return `<button class="btn secondary" onclick="payOrder('${o.id}')">确认付款</button><button onclick="cancelOrder('${o.id}')">取消订单</button>`;if(o.status==='确认')return `<button class="btn secondary" onclick="nextStatus('${o.id}')">确认交货</button><button onclick="cancelOrder('${o.id}')">取消订单</button>`;if(o.status==='等待交货')return `<button class="btn secondary" onclick="nextStatus('${o.id}')">确认完成</button><button onclick="refundOrder('${o.id}')">申请退款</button>`;if(o.status==='完成')return `<button onclick="refundOrder('${o.id}')">申请退款</button>`;return '';}
function orders(){if(!current())return shell('我的订单','<div class="empty"><strong>▣</strong>登录后查看订单<br><a class="btn" href="#/login">去登录</a></div>');let html=data.orders.map(o=>`<div class="order-card"><b>订单号 ${o.id}</b><span class="status">　${o.status}</span><p class="muted">${o.date} · ${o.items.length} 件服务</p><b>¥${o.total}</b><div>${orderActions(o)}</div></div>`).join('');return shell('我的订单',html||'<div class="empty"><strong>▣</strong>还没有订单，去挑选喜欢的服务吧</div>')}
function payOrder(id){let o=data.orders.find(x=>x.id===id);if(o.status!=='未付款')return toast('当前状态不可付款');o.status='确认';save(data);render();toast('付款成功，订单已确认')}
function nextStatus(id){let o=data.orders.find(x=>x.id===id);if(o.status==='确认')o.status='等待交货';else if(o.status==='等待交货')o.status='完成';else return toast('当前状态不可推进');save(data);render();toast('订单状态已更新')}
function cancelOrder(id){let o=data.orders.find(x=>x.id===id);if(!['未付款','确认'].includes(o.status))return toast('制作或交货后不可取消，请申请退款');o.status='已取消';save(data);render();toast('订单已取消')}
function refundOrder(id){let o=data.orders.find(x=>x.id===id);if(!['等待交货','完成'].includes(o.status))return toast('当前状态不可申请退款');o.status='退款处理中';save(data);render();toast('退款申请已提交')}
function messages(){if(!requireLogin('/messages'))return '';let u=current(),title=u.role==='merchant'?'商家消息（客户视角）':'消息中心（买家视角）';return shell(title,`<div class="message-card"><b>平台助手</b><p>${u.role==='merchant'?'查看客户咨询并及时回复，回复会同步给买家。':'这里是你与创作者的沟通记录。下单前请确认交付内容与修改次数。'}</p></div>${data.messages.map(m=>`<div class="message-card"><b>${esc(m.from)}</b><span class="tag">${m.fromRole==='merchant'?'商家':'买家'}</span><span class="muted"> · ${m.time}</span><p>${esc(m.text)}</p></div>`).join('')}<form onsubmit="sendMessage(event)" class="message-card"><div class="field"><textarea name="text" required placeholder="${u.role==='merchant'?'回复客户…':'输入消息…'}"></textarea></div><button class="btn">发送消息</button></form>`)}
function sendMessage(e){e.preventDefault();let text=new FormData(e.target).get('text'),u=current();data.messages.push({id:Date.now(),from:u.name,fromRole:u.role,text,time:'刚刚'});save(data);render();toast('消息已发送')}
function merchant(){if(!current()||current().role!=='merchant')return shell('商家后台','<div class="empty"><strong>♢</strong>请使用商家账号登录<br><a class="btn" href="#/login">去登录</a></div>');let mine=data.products.filter(p=>p.seller===current().name||current().email==='merchant@demo.com');return `<section class="section"><div class="section-head"><div><p class="eyebrow">MERCHANT STUDIO</p><h2>商家工作台</h2></div><button class="btn" onclick="newProduct()">+ 发布服务</button></div><div class="admin-grid"><div class="stat"><span>在售服务</span><strong>${mine.filter(p=>p.active).length}</strong></div><div class="stat"><span>待处理订单</span><strong>${data.orders.filter(o=>o.status==='未付款'||o.status==='确认').length}</strong></div><div class="stat"><span>客户消息</span><strong>${data.messages.length}</strong></div></div><h3>服务管理</h3><table class="table"><tr><th>服务</th><th>价格</th><th>状态</th><th>操作</th></tr>${mine.map(p=>`<tr><td>${esc(p.name)}</td><td>¥${p.price}</td><td>${p.active?'在售':'已下架'}</td><td><button onclick="toggleProduct('${p.id}')">${p.active?'下架':'上架'}</button></td></tr>`).join('')}</table><h3>订单管理</h3>${data.orders.map(o=>`<div class="admin-card">订单 ${o.id}　<span class="status">${o.status}</span>　¥${o.total} ${merchantOrderActions(o)}</div>`).join('')||'<p class="muted">暂无订单</p>'}<h3>客户聊天</h3><div class="message-card">${data.messages.map(m=>`<p><b>${esc(m.from)}</b>（${m.fromRole==='buyer'?'客户':'商家'}）：${esc(m.text)}</p>`).join('')}<form onsubmit="sendMessage(event)"><textarea name="text" required placeholder="回复客户…"></textarea><br><button class="btn">回复客户</button></form></div></section>`}
function merchantOrderActions(o){if(['未付款','确认'].includes(o.status))return `<button class="btn secondary" onclick="merchantAdvance('${o.id}')">${o.status==='未付款'?'等待付款':'确认接单'}</button><button onclick="cancelOrder('${o.id}')">取消订单</button>`;if(o.status==='等待交货')return `<button class="btn secondary" onclick="nextStatus('${o.id}')">标记已交货</button>`;return '<span class="muted">无可用操作</span>'}
function merchantAdvance(id){let o=data.orders.find(x=>x.id===id);if(o.status==='未付款')return toast('等待买家付款后才能确认订单');nextStatus(id)}
function toggleProduct(id){let p=data.products.find(x=>x.id===id);p.active=!p.active;save(data);render();toast(p.active?'服务已上架':'服务已下架')}
function newProduct(){let name=prompt('服务名称');if(!name)return;let price=Number(prompt('价格','299'));data.products.push({id:'p'+Date.now(),cat:'painting',name,price:price||299,img:A+'[002566].png',seller:current().name,desc:'新发布的定制服务',active:true,isNew:true});save(data);render();toast('服务已发布')}
function account(){let u=current();return u?shell('个人中心',`<div class="admin-card"><h3>${esc(u.name)}</h3><p>${esc(u.email)} · ${u.role==='merchant'?'创作者':'买家'}</p><button class="btn secondary" onclick="logout()">退出登录</button></div>`):auth(false)}
function logout(){localStorage.removeItem('linggan-user');toast('已退出登录');go('/')}
function updateBadges(){let c=$('#cart-badge');if(c)c.textContent=data.cart.length;let m=$('#message-badge');if(m)m.textContent=data.messages.length}
function render(){data=load();updateBadges();let raw=location.hash.slice(1)||'/';let query=raw.includes('?')?new URLSearchParams(raw.split('?')[1]):new URLSearchParams(),path=raw.split('?')[0],[route,arg]=path.split('/').filter(Boolean);let html=route==='category'?category(arg,query.get('view')||'product'):route==='product'?product(arg):route==='cart'?cart():route==='login'?auth(false):route==='register'?auth(true):route==='orders'?orders():route==='messages'?messages():route==='merchant'?merchant():route==='account'?account():home();$('#app').innerHTML=html;document.querySelectorAll('.main-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href').includes(arg||route)));let u=current();$('#account-link').textContent=u?u.name:'登录'}
window.addEventListener('hashchange',render);window.addEventListener('DOMContentLoaded',render);updateBadges();
